### ISSUE TITLE
Question | Does memoize-cache-decorator works across node workers?

### ISSUE THREAD

**Issue by talkl** [edwinm/memoize-cache-decorator#3]
Hi Edwin,

We are using your package in our company's node backend server.
We were wondering if the cache is persisted across different workers in the node process or is it per worker?

Thank you,
Tal

**Comment by talkl** [comment]
@edwinm I tested and it's not persisted across workers, probably because every worker has it's own memory. So maybe I would add it to the docs so people can understand the consequences.

**Comment by edwinm** [comment]
It's indeed not persistent across workers. It's an implementation of memoize. Maybe the word "cache" made you think it implements the Cache interface (https://developer.mozilla.org/en-US/docs/Web/API/Cache)? That's not the case.
